project 'kit.xcodeproj'

pod 'Mixpanel'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'kit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kit

  target 'kitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
